### ISSUE TITLE
How delete text "Trial" 

### ISSUE THREAD

**Issue by YaroslavG** [Wikitude/wikitude-cordova-plugin-samples#19]
Hello, I use your plugin! Its perfect work! and have some questions:
How I can delete text "Trial" when the camera is open?

**Comment by aridiana123** [comment]
hello 
iam newbie AR and I've project for my studies make 3D AR method location based tracking 
I try using wikitude but I don't know step by step how to dd it..
can u teach me ??
JavaScript API or Native API I can use?? 
thank you :)

**Comment by AndreasSchacherbauerWikitude** [comment]
hi @aridiana123, what do you mean by 'location based tracking'? Geo AR or 2d image recognition? The Wikitude Cordova plugin is based on the Wikitude SDK with JavaScript API, so if you want to use Cordova, you have to work with the JS API SDK.

For more information, please contact sales [at] wikitude [dot] com

**Comment by aridiana123** [comment]
@AndreasSchacherbauerWikitude  thank you for reply 
I want make geo AR with 3D object...
I must using cordova and JS API SDK? :)

**Comment by AndreasSchacherbauerWikitude** [comment]
hi @aridiana123, here is a [link](http://www.wikitude.com/developer/documentation/phonegap) to our Cordova documentation. It also includes examples on how to render 3d objects at specific geo locations. I guess with this documentation you should be able to finish your application.

**Comment by aridiana123** [comment]
what i do first ?? make geolocation or 3D model ??
i must instal 3D Encoder for Windows too??
send me link about that..
thank you for tutor :)

**Comment by AndreasSchacherbauerWikitude** [comment]
Simply refer to [this](https://github.com/Wikitude/wikitude-sdk-samples/tree/master/3_3dModels_6_3dModelAtGeoLocation) example and the corresponding [documentation](http://www.wikitude.com/external/doc/documentation/latest/ios/3dmodels.html#3dModelAtGeoLocation).
You need to have a .fbx file and then use our 3D Encoder to get a .wt3 file. What tool you use to get to the .fbx doesn't matter (I don't believe that cordova can create .fbx files ;) )

**Comment by aridiana123** [comment]
hai  I try to setup javascript wikitude SDK but I not success to setup, I try step by step on link documentation wikitude to setup it
are u have solution ?
 

    On Thursday, November 3, 2016 9:28 PM, "Andreas Schacherbauer @Wikitude" <notifications@github.com> wrote:
 

 Simply refer to this example and the corresponding documentation.
You need to have a .fbx file and then use our 3D Encoder to get a .wt3 file. What tool you use to get to the .fbx doesn't matter (I don't believe that cordova can create .fbx files ;) )—

**Comment by AndreasSchacherbauerWikitude** [comment]
If you don't tell us what the problem is, It's very unlikely that I can help you. Did you also had a look at our example application for Cordova?

**Comment by huzairuje** [comment]
Hei  AndreasSchacherbauerWikitude, i have the EDU license yesterday, but it doesn't show like pnagele said. 
![screenshot_2016-11-09-22-01-24](https://cloud.githubusercontent.com/assets/4037159/20166698/19ee4430-a749-11e6-9c4a-d328333de287.png)
![screenshot_2016-11-09-21-49-41](https://cloud.githubusercontent.com/assets/4037159/20166697/19ed95d0-a749-11e6-9287-0e90c3611b0f.png)

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi @huzairuje, 
As you already wrote an email to us regarding your license key, I will not answer here. You will receive a reply to your mails shortly.

**Comment by aridiana123** [comment]
haii.. 
I run the sample of wikitude but this project is error. how about that?
![abs](https://cloud.githubusercontent.com/assets/23161650/20616394/05386cd4-b31d-11e6-96fe-9949bdd1e177.png)

**Comment by aridiana123** [comment]
this wikitude can made dynamic application ?? can I have free EDU license key too

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi @aridiana123, 
what is a dynamic application for you? Regarding an EDU license, please contact edu@wikitude.com for more information.

**Comment by aridiana123** [comment]
@AndreasSchacherbauerWikitude i interest to make application like wikitude drive AR Navigation for Smartphones
are u have tutorial about that?

**Comment by aridiana123** [comment]
@AndreasSchacherbauerWikitude hay andreas 
if i want to wikitude 3d model AR Navigation at geo for Smartphones, i must make on unity or no?
please replay 
my project does't load 3d model

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi @aridiana123, we don't have a tutorial for an application like Wikitude Drive, sorry.
Currently our Unity plugin does not support Geo AR but our Wikitude JS API SDK includes Geo AR functionality plus rendering of 3d models (You can convert any .fbx into our own .wt3 file format using the Wikitude 3d Encoder).
