### ISSUE TITLE
iOS 9 Samples for POIs crash every 3 seconds in the camera view.

### ISSUE THREAD

**Issue by qbunt** [Wikitude/wikitude-cordova-plugin-samples#40]
The iOS 9 Cordova plugin crashes on all points of interest examples. It appears that the compass pops up for a second and then goes right back to camera view in a loop. This is a pretty severe issue, as all POIs in the wikitude SDK crash, even with existing installs of applications.

Please fix this issue, we paid for a license and your product isn't working as advertised.

**Comment by qbunt** [comment]
@Wikitude Any update on this issue? We paid for a license, this plugin doesn't build, and now we have an app we can't update. Any idea on a resolution?

**Comment by pnagele** [comment]
We are aware of this issue and are working on a resolution. We aim for a first fix this week:
http://www.wikitude.com/developer/developer-forum/-/message_boards/message/773623

**Comment by qbunt** [comment]
@pnagele What is the status of a fix?

**Comment by pnagele** [comment]
Hi, check out the branch release/v5.0.1-3.2.0 of the plugin itself (https://github.com/Wikitude/wikitude-cordova-plugin/tree/release/v5.0.1-3.2.0). This fixes the compass problem. The branch is not yet final and hence not yet integrated into the sample app. But you can update the plugin you are using from the branch above.

**Comment by qbunt** [comment]
Thanks for the update @pnagele

**Comment by qbunt** [comment]
@pnagele Can you tell me when you're planning on merging this into main? It doesn't look like there are any tests in this repo, are you planning on having people just test this and see how it goes?

**Comment by qbunt** [comment]
Given that there have been several maintenance commits to this repo and no update to this issue, I'm closing it. If this has been fixed, that's great, but the samples should be updated as well.
